/* iTech Global Search - additive, mobile-friendly */
(function(){
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 function init(){if(document.getElementById('itechGlobalSearch'))return;const host=document.querySelector('.dash-main');if(!host||!window.sb)return;const w=document.createElement('div');w.id='itechGlobalSearch';w.style='position:relative;max-width:620px;margin:0 0 16px';w.innerHTML='<input id="itechGlobalSearchInput" type="search" placeholder="🔎 Search customer, mobile, vehicle, service, invoice..." style="width:100%;box-sizing:border-box;padding:13px 15px;border:1px solid #d9e4f1;border-radius:13px;background:#fff;box-shadow:0 8px 22px rgba(17,50,91,.06)"><div id="itechGlobalSearchResults" style="display:none;position:absolute;z-index:3000;left:0;right:0;top:54px;background:#fff;border:1px solid #d9e4f1;border-radius:14px;box-shadow:0 18px 45px rgba(17,50,91,.16);max-height:420px;overflow:auto"></div>';host.insertBefore(w,host.firstChild);const input=w.querySelector('#itechGlobalSearchInput'),box=w.querySelector('#itechGlobalSearchResults');let timer;
 async function search(q){if(q.length<2){box.style.display='none';return}box.style.display='block';box.innerHTML='<div style="padding:14px;color:#71819b">Searching…</div>';const out=[];try{const c=await sb.from('customers').select('id,full_name,mobile,email').or(`full_name.ilike.%${q}%,mobile.ilike.%${q}%,email.ilike.%${q}%`).limit(8);(c.data||[]).forEach(x=>out.push({i:'👤',t:x.full_name,s:[x.mobile,x.email].filter(Boolean).join(' · '),u:'customers.html'}))}catch(_){ }try{const v=await sb.from('vehicle_insurance').select('id,customer_name,mobile,vehicle_number,policy_number').or(`customer_name.ilike.%${q}%,mobile.ilike.%${q}%,vehicle_number.ilike.%${q}%,policy_number.ilike.%${q}%`).limit(8);(v.data||[]).forEach(x=>out.push({i:'🚗',t:x.vehicle_number||x.customer_name,s:[x.mobile,x.policy_number].filter(Boolean).join(' · '),u:'vehicle-insurance.html'}))}catch(_){ }try{const s=await sb.from('service_jobs').select('id,job_number,device_type,brand,model').or(`job_number.ilike.%${q}%,device_type.ilike.%${q}%,brand.ilike.%${q}%,model.ilike.%${q}%`).limit(8);(s.data||[]).forEach(x=>out.push({i:'🛠️',t:x.job_number,s:[x.brand,x.model,x.device_type].filter(Boolean).join(' '),u:'services.html'}))}catch(_){ }box.innerHTML=out.length?out.slice(0,15).map(x=>`<a href="${x.u}" style="display:flex;gap:10px;padding:11px 13px;text-decoration:none;color:#10284b;border-bottom:1px solid #edf2f7"><span>${x.i}</span><span><b>${esc(x.t)}</b><small style="display:block;color:#71819b">${esc(x.s)}</small></span></a>`).join(''):'<div style="padding:14px;color:#71819b">No matching records.</div>'}
 input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>search(input.value.trim()),250)});document.addEventListener('click',e=>{if(!w.contains(e.target))box.style.display='none'});
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
