/* Excel-style Today's Work sheet + edit-only workflow. */
(function(){
  const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
  const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
  const built=[['e_filing','E-Filing'],['e_payment','E-Payment'],['print_amount','Print'],['scanning','Scanning'],['other_works','Other Works']];
  function today(){const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
  function addCss(){if(document.getElementById('rg-css'))return;const s=document.createElement('style');s.id='rg-css';s.textContent=`.rg-panel{margin-top:18px;background:#fff;border:1px solid #dfe8f2;border-radius:18px;padding:18px;box-shadow:0 10px 28px rgba(17,50,91,.06)}.rg-head{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}.rg-scroll{overflow:auto;margin-top:12px}.rg-table{border-collapse:collapse;width:100%;min-width:1050px}.rg-table th,.rg-table td{padding:10px;border:1px solid #dfe8f2;white-space:nowrap}.rg-table th{background:#f3f7fc;color:#526783;font-size:11px;text-transform:uppercase}.rg-table td{font-size:13px}.rg-edit{border:1px solid #cbd9ea;background:#fff;border-radius:8px;padding:6px 9px;font-weight:800;color:#1458a0;cursor:pointer}.rg-modal{position:fixed;inset:0;background:rgba(5,20,40,.45);z-index:9998;display:none;align-items:center;justify-content:center;padding:18px}.rg-modal.show{display:flex}.rg-box{background:#fff;width:min(620px,100%);max-height:90vh;overflow:auto;border-radius:18px;padding:20px}.rg-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.rg-grid label{font-size:12px;font-weight:800;color:#39506f}.rg-grid input{width:100%;box-sizing:border-box;border:1px solid #d8e2ef;border-radius:10px;padding:10px;margin-top:5px}.rg-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:15px}@media(max-width:650px){.rg-grid{grid-template-columns:1fr}}@media print{.rg-no-print{display:none!important}.rg-panel{box-shadow:none;border:0;padding:0}.rg-table{min-width:0;font-size:9px}.rg-table th,.rg-table td{padding:5px}}`;document.head.appendChild(s)}
  async function load(){
    const host=document.getElementById('todayPanel');if(!host||document.getElementById('rgPanel'))return;
    addCss();const panel=document.createElement('section');panel.className='rg-panel';panel.id='rgPanel';panel.innerHTML=`<div class="rg-head"><div><p class="eyebrow">TODAY'S WORK</p><h2 style="margin:0">Today's Work Entries</h2><p class="muted">Excel-style customer rows. Each work type is a column.</p></div><button class="btn secondary rg-no-print" id="rgPrint">🖨️ Print Sheet</button></div><div class="rg-scroll"><table class="rg-table"><thead id="rgHead"></thead><tbody id="rgBody"></tbody></table></div>`;host.insertBefore(panel,host.firstChild);
    const modal=document.createElement('div');modal.className='rg-modal';modal.id='rgModal';modal.innerHTML=`<div class="rg-box"><h2 style="margin-top:0">Edit Work Entry</h2><div class="rg-grid"><label>E-Filing<input id="rgFiling" type="number" min="0" step="0.01"></label><label>E-Payment<input id="rgEpay" type="number" min="0" step="0.01"></label><label>Print<input id="rgPrintAmt" type="number" min="0" step="0.01"></label><label>Scanning<input id="rgScan" type="number" min="0" step="0.01"></label><label>Other Works<input id="rgOther" type="number" min="0" step="0.01"></label><label>Discount<input id="rgDiscount" type="number" min="0" step="0.01"></label><label>Paid Amount<input id="rgPaid" type="number" min="0" step="0.01"></label><label>Balance<input id="rgBalance" type="number" min="0" step="0.01" readonly></label></div><div class="rg-actions"><button class="btn secondary" id="rgCancel">Cancel</button><button class="btn primary" id="rgSave">Save Changes</button></div><div id="rgMsg" class="status"></div></div>`;document.body.appendChild(modal);
    let editing=null;
    document.getElementById('rgCancel').onclick=()=>modal.classList.remove('show');
    ['rgFiling','rgEpay','rgPrintAmt','rgScan','rgOther','rgDiscount','rgPaid'].forEach(id=>document.getElementById(id).addEventListener('input',()=>{const gross=['rgFiling','rgEpay','rgPrintAmt','rgScan','rgOther'].reduce((s,x)=>s+Number(document.getElementById(x).value||0),0);const net=Math.max(gross-Number(document.getElementById('rgDiscount').value||0),0);document.getElementById('rgBalance').value=Math.max(net-Number(document.getElementById('rgPaid').value||0),0).toFixed(2)}));
    document.getElementById('rgSave').onclick=async()=>{if(!editing)return;const gross=['rgFiling','rgEpay','rgPrintAmt','rgScan','rgOther'].reduce((s,x)=>s+Number(document.getElementById(x).value||0),0);const discount=Number(document.getElementById('rgDiscount').value||0),paid=Number(document.getElementById('rgPaid').value||0),net=Math.max(gross-discount,0),balance=Math.max(net-paid,0);const r=await sb.from('daily_work_entries').update({e_filing:Number(document.getElementById('rgFiling').value||0),e_payment:Number(document.getElementById('rgEpay').value||0),print_amount:Number(document.getElementById('rgPrintAmt').value||0),scanning:Number(document.getElementById('rgScan').value||0),other_works:Number(document.getElementById('rgOther').value||0),discount,paid_amount:paid,balance_amount:balance}).eq('id',editing.id);if(r.error){document.getElementById('rgMsg').textContent=r.error.message;return}modal.classList.remove('show');await render()};
    document.getElementById('rgPrint').onclick=()=>window.print();
    async function render(){
      const q=await sb.from('daily_work_entries').select('id,customer_id,created_at,e_filing,e_payment,print_amount,scanning,other_works,discount,paid_amount,balance_amount,entry_type,extra_entries').eq('work_date',today()).order('created_at',{ascending:true});
      if(q.error){document.getElementById('rgBody').innerHTML=`<tr><td>${esc(q.error.message)}</td></tr>`;return}
      const rows=q.data||[];const ids=[...new Set(rows.map(r=>r.customer_id).filter(Boolean))];let cm=new Map();if(ids.length){const c=await sb.from('customers').select('id,full_name,mobile').in('id',ids);(c.data||[]).forEach(x=>cm.set(String(x.id),x))}
      const extraNames=[];rows.forEach(r=>(Array.isArray(r.extra_entries)?r.extra_entries:[]).forEach(x=>{if(x.name&&!extraNames.includes(x.name))extraNames.push(x.name)}));
      const groups=new Map();rows.forEach(r=>{const key=r.entry_type==='cash_sale'?'cash-sale':String(r.customer_id||r.id);const g=groups.get(key)||{id:r.id,customer_id:r.customer_id,entry_type:r.entry_type,rows:[]};g.rows.push(r);groups.set(key,g)});
      const headers=['Customer','E-Filing','E-Payment','Print','Scanning','Other Works',...extraNames,'Discount','Net Amount','Paid','Balance','Action'];document.getElementById('rgHead').innerHTML='<tr>'+headers.map(h=>`<th>${esc(h)}</th>`).join('')+'</tr>';
      document.getElementById('rgBody').innerHTML=Array.from(groups.values()).map(g=>{const sum=(key)=>g.rows.reduce((s,r)=>s+Number(r[key]||0),0);const ex={};g.rows.forEach(r=>(Array.isArray(r.extra_entries)?r.extra_entries:[]).forEach(x=>ex[x.name]=(ex[x.name]||0)+Number(x.amount||0)));const gross=sum('e_filing')+sum('e_payment')+sum('print_amount')+sum('scanning')+sum('other_works')+Object.values(ex).reduce((a,b)=>a+b,0);const disc=sum('discount'),net=Math.max(gross-disc,0),paid=sum('paid_amount')||0,balance=sum('balance_amount')||Math.max(net-paid,0);const name=g.entry_type==='cash_sale'?'Cash Sale':(cm.get(String(g.customer_id))?.full_name||'Customer');const cells=[name,sum('e_filing'),sum('e_payment'),sum('print_amount'),sum('scanning'),sum('other_works'),...extraNames.map(n=>ex[n]||0),disc,net,paid,balance];return '<tr>'+cells.map((v,i)=>`<td>${i===0?`<b>${esc(v)}</b>`:(Number(v)?money(v):'—')}</td>`).join('')+`<td><button class="rg-edit" data-edit="${esc(g.id)}">✏️ Edit</button></td></tr>`}).join('')||`<tr><td colspan="${headers.length}">No work entries today.</td></tr>`;
      document.querySelectorAll('[data-edit]').forEach(btn=>btn.onclick=()=>{const g=Array.from(groups.values()).find(x=>String(x.id)===String(btn.dataset.edit));const r=g?.rows?.[0];if(!r)return;editing=r;document.getElementById('rgFiling').value=r.e_filing||0;document.getElementById('rgEpay').value=r.e_payment||0;document.getElementById('rgPrintAmt').value=r.print_amount||0;document.getElementById('rgScan').value=r.scanning||0;document.getElementById('rgOther').value=r.other_works||0;document.getElementById('rgDiscount').value=r.discount||0;document.getElementById('rgPaid').value=r.paid_amount||0;document.getElementById('rgBalance').value=r.balance_amount||0;modal.classList.add('show')});
    }
    await render();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();
})();
